#!/bin/sh
stagedFiles=$(git diff --staged --name-only)
echo "Running mvn spotless:apply for code formatting..."
mvn spotless:apply
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done